package planning

import timeentriespkg "welloresto-api/internal/modules/planning/timeentries"

type PlanningTimeEntry = timeentriespkg.PlanningTimeEntry
type PlanningTimeEntryStartRequest = timeentriespkg.PlanningTimeEntryStartRequest
type PlanningTimeEntryStopRequest = timeentriespkg.PlanningTimeEntryStopRequest
type PlanningTimeEntryManualCreateRequest = timeentriespkg.PlanningTimeEntryManualCreateRequest
type PlanningTimeEntryCorrectionRequest = timeentriespkg.PlanningTimeEntryCorrectionRequest
type PlanningTimeEntryDeleteRequest = timeentriespkg.PlanningTimeEntryDeleteRequest
