package upsell

import (
	"time"

	"welloresto-api/internal/models"
)

// Source constants identify the origin of an upsell suggestion.
const (
	SourcePattern          = "pattern"
	SourceLLM              = "llm"
	SourceFeaturedFallback = "featured_fallback"
	SourceCachedPattern    = "cached_pattern"
	SourceCachedLLM        = "cached_llm"
	SourceDisabled         = "disabled"
	SourceErrorFallback    = "error_fallback"
)

// Channel constants identify which platform triggered a GenerateUpsell call.
// Persisted on upsell_suggestions.channel for per-platform analytics.
const (
	ChannelPOS   = "POS"
	ChannelSNO   = "SNO"
	ChannelKiosk = "KIOSK"
)

// Suggestion is the full persisted upsell suggestion record.
type Suggestion struct {
	ID             string          `json:"id"`
	MerchantID     string          `json:"merchant_id"`
	OrderID        *string         `json:"order_id,omitempty"`
	CartSignature  string          `json:"cart_signature"`
	SuggestedItems []SuggestedItem `json:"suggested_items"`
	Source         string          `json:"source"`
	AcceptedItems  []AcceptedItem  `json:"accepted_items,omitempty"`
	RevenueImpact  *float64        `json:"revenue_impact,omitempty"`
	LLMProvider    *string         `json:"llm_provider,omitempty"`
	LLMModel       *string         `json:"llm_model,omitempty"`
	TokensIn       *int            `json:"tokens_in,omitempty"`
	TokensOut      *int            `json:"tokens_out,omitempty"`
	LatencyMs      int             `json:"latency_ms"`
	CreatedAt      time.Time       `json:"created_at"`
}

// SuggestedItem represents a single product proposed during upsell.
// Title is an appetising phrase generated by the LLM or rule engine.
// Score is a relevance score in range 0.0 – 1.0.
// Name, Price, ImageURL are enriched product fields included for analytics.
// Product carries the full product configuration (attributes, options,
// per-channel prices, allergens, tags) as loaded by MenuRepository.GetProduct,
// uncleaned — each channel (POS/Kiosk/SNO) applies its own cleanup on top.
// It is additive and nil-able so existing consumers relying only on the flat
// fields above keep working unchanged.
type SuggestedItem struct {
	ProductID string               `json:"product_id"`
	Title     string               `json:"title"`
	Score     float64              `json:"score"`
	Name      string               `json:"name"`
	Price     int64                `json:"price"`
	ImageURL  *string              `json:"image_url,omitempty"`
	Product   *models.ProductEntry `json:"product,omitempty"`
}

// AcceptedItem records which suggested product was ultimately ordered.
// UnitPrice is in centimes, matching models.ProductEntry.Price.
type AcceptedItem struct {
	ProductID string `json:"product_id"`
	Quantity  int    `json:"quantity"`
	UnitPrice int64  `json:"unit_price"`
}

// CreateSuggestionParams holds the data required to persist a new suggestion.
// Source must be one of the Source* constants. Channel must be one of the
// Channel* constants and identifies which platform triggered the call.
type CreateSuggestionParams struct {
	MerchantID     string
	CartSignature  string
	SuggestedItems []SuggestedItem
	Source         string
	Channel        string
	LLMProvider    *string
	LLMModel       *string
	TokensIn       *int
	TokensOut      *int
	LatencyMs      int
}

// RecordAcceptanceParams carries the acceptance data written back after order creation.
type RecordAcceptanceParams struct {
	OrderID       string
	AcceptedItems []AcceptedItem
	RevenueImpact float64
}
