-- Tranche 1 HACCP (temperatures)
-- 1) restaurant_id -> merchant_id
-- 2) soft delete support for zones
-- 3) session-based batch insert support
-- 4) column sizes aligned with prefixed IDs generated by helpers.GeneratePrefixedID

-- =========================
-- haccp_settings
-- =========================
ALTER TABLE haccp_settings
  MODIFY COLUMN id VARCHAR(80) NOT NULL,
  CHANGE COLUMN restaurant_id merchant_id VARCHAR(64) NOT NULL;

ALTER TABLE haccp_settings
  DROP INDEX uq_haccpsettings_restaurant,
  ADD UNIQUE KEY uq_haccpsettings_merchant (merchant_id);

-- =========================
-- temperature_zones
-- =========================
ALTER TABLE temperature_zones
  MODIFY COLUMN id VARCHAR(64) NOT NULL,
  CHANGE COLUMN restaurant_id merchant_id VARCHAR(64) NOT NULL,
  ADD COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE temperature_zones
  DROP INDEX idx_tempzones_restaurant,
  ADD KEY idx_tempzones_merchant (merchant_id),
  ADD KEY idx_tempzones_merchant_enabled (merchant_id, enabled);

-- =========================
-- temperature_sessions
-- =========================
CREATE TABLE temperature_sessions (
  id         VARCHAR(64) NOT NULL,
  merchant_id VARCHAR(64) NOT NULL,
  created_by VARCHAR(255) NOT NULL,
  enabled    TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tempsess_merchant_created (merchant_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- temperature_readings
-- =========================
ALTER TABLE temperature_readings
  DROP FOREIGN KEY fk_tempread_zone;

ALTER TABLE temperature_readings
  MODIFY COLUMN id VARCHAR(64) NOT NULL,
  CHANGE COLUMN restaurant_id merchant_id VARCHAR(64) NOT NULL,
  MODIFY COLUMN zone_id VARCHAR(64) NOT NULL,
  ADD COLUMN session_id VARCHAR(64) NOT NULL AFTER id,
  ADD COLUMN comment TEXT NULL AFTER signature,
  ADD COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE temperature_readings
  DROP INDEX idx_tempread_restaurant_created,
  ADD KEY idx_tempread_merchant_created (merchant_id, created_at),
  ADD KEY idx_tempread_session (session_id),
  ADD KEY idx_tempread_merchant_session (merchant_id, session_id);

ALTER TABLE temperature_readings
  ADD CONSTRAINT fk_tempread_zone FOREIGN KEY (zone_id)
    REFERENCES temperature_zones(id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_tempread_session FOREIGN KEY (session_id)
    REFERENCES temperature_sessions(id) ON DELETE CASCADE;

/*
============================================================
SCRIPTS DE CREATION (INSTALLATION FROM SCRATCH)
============================================================
Ces scripts sont fournis en complément pour créer les tables HACCP
directement sur une base vierge.

CREATE TABLE haccp_settings (
  id                           VARCHAR(80) NOT NULL,
  merchant_id                  VARCHAR(64) NOT NULL,
  temp_entry_required          TINYINT(1) NOT NULL DEFAULT 0,
  temp_corrective_actions      TINYINT(1) NOT NULL DEFAULT 0,
  temp_block_past_dates        TINYINT(1) NOT NULL DEFAULT 0,
  traceability_product_name    TINYINT(1) NOT NULL DEFAULT 0,
  traceability_block_past_dates TINYINT(1) NOT NULL DEFAULT 0,
  cleaning_photo               TINYINT(1) NOT NULL DEFAULT 0,
  cleaning_block_past_dates    TINYINT(1) NOT NULL DEFAULT 0,
  reception_other_products     TINYINT(1) NOT NULL DEFAULT 0,
  reception_control_sample     TINYINT(1) NOT NULL DEFAULT 0,
  reception_block_past_dates   TINYINT(1) NOT NULL DEFAULT 0,
  reception_photo              TINYINT(1) NOT NULL DEFAULT 0,
  reception_non_conformities   TINYINT(1) NOT NULL DEFAULT 0,
  oils_block_past_dates        TINYINT(1) NOT NULL DEFAULT 0,
  oils_polar_compound_rate     TINYINT(1) NOT NULL DEFAULT 0,
  oils_photo                   TINYINT(1) NOT NULL DEFAULT 0,
  production_block_past_dates  TINYINT(1) NOT NULL DEFAULT 0,
  production_traceability      TINYINT(1) NOT NULL DEFAULT 0,
  cooling_block_past_dates     TINYINT(1) NOT NULL DEFAULT 0,
  freezing_block_past_dates    TINYINT(1) NOT NULL DEFAULT 0,
  reheating_block_past_dates   TINYINT(1) NOT NULL DEFAULT 0,
  holding_block_past_dates     TINYINT(1) NOT NULL DEFAULT 0,
  holding_corrective_actions   TINYINT(1) NOT NULL DEFAULT 0,
  notif_authorization          TINYINT(1) NOT NULL DEFAULT 0,
  notif_security               TINYINT(1) NOT NULL DEFAULT 0,
  created_at                   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_haccpsettings_merchant (merchant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE temperature_zones (
  id               VARCHAR(64) NOT NULL,
  merchant_id      VARCHAR(64) NOT NULL,
  name             VARCHAR(150) NOT NULL,
  target_temp_min  DECIMAL(5,2) NOT NULL,
  target_temp_max  DECIMAL(5,2) NOT NULL,
  enabled          TINYINT(1) NOT NULL DEFAULT 1,
  deleted_at       DATETIME NULL,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tempzones_merchant (merchant_id),
  KEY idx_tempzones_merchant_enabled (merchant_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE temperature_sessions (
  id               VARCHAR(64) NOT NULL,
  merchant_id      VARCHAR(64) NOT NULL,
  created_by       VARCHAR(255) NOT NULL,
  enabled          TINYINT(1) NOT NULL DEFAULT 1,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tempsess_merchant_created (merchant_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE temperature_readings (
  id               VARCHAR(64) NOT NULL,
  session_id       VARCHAR(64) NOT NULL,
  merchant_id      VARCHAR(64) NOT NULL,
  zone_id          VARCHAR(64) NOT NULL,
  value            DECIMAL(5,2) NOT NULL,
  status           ENUM('ok','alert','critical') NOT NULL DEFAULT 'ok',
  photo_url        VARCHAR(512) NULL,
  signature        MEDIUMTEXT NULL,
  comment          TEXT NULL,
  created_by       VARCHAR(255) NOT NULL,
  enabled          TINYINT(1) NOT NULL DEFAULT 1,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tempread_merchant_created (merchant_id, created_at),
  KEY idx_tempread_zone (zone_id),
  KEY idx_tempread_session (session_id),
  KEY idx_tempread_merchant_session (merchant_id, session_id),
  CONSTRAINT fk_tempread_zone FOREIGN KEY (zone_id)
    REFERENCES temperature_zones(id) ON DELETE CASCADE,
  CONSTRAINT fk_tempread_session FOREIGN KEY (session_id)
    REFERENCES temperature_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/
