package discounts

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// TimeOfDay represents a time of day in HH:MM format for JSON serialization
type TimeOfDay time.Time

// MarshalJSON formats TimeOfDay as "HH:MM"
func (t TimeOfDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(time.Time(t).Format("15:04"))
}

// UnmarshalJSON parses "HH:MM" format from JSON
func (t *TimeOfDay) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := time.Parse("15:04", s)
	if err != nil {
		return err
	}
	*t = TimeOfDay(parsed)
	return nil
}

// DiscountUnit represents the unit type for discount calculation
type DiscountUnit string

const (
	DiscountUnitPercentage DiscountUnit = "PERCENTAGE"
	DiscountUnitCurrency   DiscountUnit = "CURRENCY"
	DiscountUnitNewPrice   DiscountUnit = "NEWPRICE"
)

// OrderType represents the order type for which the discount applies
type OrderType string

const (
	OrderTypeInDining OrderType = "IN"
	OrderTypeDelivery OrderType = "DELIVERY"
)

// MinOrderUnit represents the unit for minimum order requirements
type MinOrderUnit string

const (
	MinOrderUnitCurrency MinOrderUnit = "CURRENCY"
	MinOrderUnitQuantity MinOrderUnit = "QUANTITY"
)

// MaxDiscountUnit represents the unit for maximum discount cap
type MaxDiscountUnit string

const (
	MaxDiscountUnitCurrency MaxDiscountUnit = "CURRENCY"
	MaxDiscountUnitQuantity MaxDiscountUnit = "QUANTITY"
)

// DiscountScope distinguishes product-level discounts from cart-wide (codes promo panier) discounts.
type DiscountScope string

const (
	DiscountScopeProduct    DiscountScope = "PRODUCT"
	DiscountScopeOrderTotal DiscountScope = "ORDER_TOTAL"
)

// DiscountProduct represents a product associated with a discount and its custom price
type DiscountProduct struct {
	ID         string `json:"id"`
	DiscountID string `json:"discount_id"`
	ProductID  string `json:"product_id"` // UUID
	NewPrice   *int64 `json:"new_price,omitempty"`
	Enabled    bool   `json:"enabled"`
}

// DiscountSchedule represents time slot availability for a discount
type DiscountSchedule struct {
	ScheduleID    string    `json:"schedule_id"`
	DiscountID    string    `json:"discount_id"`
	DayOfWeek     int       `json:"day_of_week"`    // 1 = lundi, ..., 7 = dimanche (1-7 standard)
	AvailableFrom TimeOfDay `json:"available_from"` // HH:MM format
	AvailableTo   TimeOfDay `json:"available_to"`   // HH:MM format
	Enabled       bool      `json:"enabled"`
}

// Discount represents a complete discount/promotion
type Discount struct {
	DiscountID         string             `json:"discount_id"`
	MerchantID         string             `json:"merchant_id"`
	DiscountName       string             `json:"discount_name"`
	DiscountDesc       string             `json:"discount_desc"`
	PreferredOrder     int                `json:"preferred_order"`
	DiscountCode       *string            `json:"discount_code,omitempty"`
	OrderType          *OrderType         `json:"order_type,omitempty"` // nil = all types
	DiscountValue      *int               `json:"discount_value"`
	DiscountUnit       DiscountUnit       `json:"discount_unit"`
	ValidFrom          time.Time          `json:"valid_from"`         // UTC
	ValidTo            *time.Time         `json:"valid_to,omitempty"` // UTC
	MinOrderValue      *float64           `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit      `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64           `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit   `json:"max_discount_unit,omitempty"`
	DiscountedQuantity int                `json:"discounted_quantity"`
	IsCumulative       bool               `json:"is_cumulative"`
	IsTimeLimited      bool               `json:"is_time_limited"`
	Available          bool               `json:"available"`
	Enabled            bool               `json:"enabled"`
	CreationDate       time.Time          `json:"creation_date"` // UTC
	Products           []DiscountProduct  `json:"products,omitempty"`
	Schedules          []DiscountSchedule `json:"schedules,omitempty"`

	// Codes promo panier (Sprint 2)
	DiscountScope             DiscountScope `json:"discount_scope"`
	MaxRedemptions            *int          `json:"max_redemptions,omitempty"`
	MaxRedemptionsPerCustomer *int          `json:"max_redemptions_per_customer,omitempty"`
}

// CreateDiscountRequest is the payload for creating a discount
type CreateDiscountRequest struct {
	DiscountID         string                  `json:"discount_id"` // UUID generated by client
	DiscountName       string                  `json:"discount_name"`
	DiscountDesc       string                  `json:"discount_desc"`
	PreferredOrder     int                     `json:"preferred_order"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      float64                 `json:"discount_value"`
	DiscountUnit       DiscountUnit            `json:"discount_unit"`
	ValidFrom          time.Time               `json:"valid_from"`
	ValidTo            *time.Time              `json:"valid_to,omitempty"`
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity int                     `json:"discounted_quantity"`
	IsCumulative       bool                    `json:"is_cumulative"`
	IsTimeLimited      bool                    `json:"is_time_limited"`
	Available          bool                    `json:"available"`
	Products           []CreateProductRequest  `json:"products,omitempty"`
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"`
	DiscountScope             DiscountScope `json:"discount_scope,omitempty"`
	MaxRedemptions            *int          `json:"max_redemptions,omitempty"`
	MaxRedemptionsPerCustomer *int          `json:"max_redemptions_per_customer,omitempty"`
}

// CreateProductRequest represents product data for discount creation
type CreateProductRequest struct {
	ProductID string `json:"product_id"` // UUID
	NewPrice  *int64 `json:"new_price,omitempty"`
}

// CreateScheduleRequest represents schedule data for discount creation
type CreateScheduleRequest struct {
	DayOfWeek     int       `json:"day_of_week"`
	AvailableFrom time.Time `json:"available_from"`
	AvailableTo   time.Time `json:"available_to"`
}

// UnmarshalJSON lit et valide un créneau saisi dans le back-office :
//   - day_of_week ISO 1 = lundi … 7 = dimanche, convention de toutes les
//     évaluations (pricing, listes Kiosk/ScanNOrder). 0 est accepté comme
//     dimanche (ancienne convention JS du back-office) et ramené à 7 —
//     stocké tel quel, un dimanche 0 n'était jamais actif ;
//   - heures "HH:MM" ou "HH:MM:SS" (heure locale du merchant) ; une heure
//     illisible est une erreur (400), elle devenait silencieusement 00:00 ;
//   - intervalle [début, fin[ avec début < fin, ou fin à 00:00 = jusqu'à
//     minuit (ex. 19:00–00:00). Tout autre créneau à l'envers est refusé :
//     il n'aurait jamais été actif.
func (s *CreateScheduleRequest) UnmarshalJSON(data []byte) error {
	type Alias struct {
		DayOfWeek     int    `json:"day_of_week"`
		AvailableFrom string `json:"available_from"`
		AvailableTo   string `json:"available_to"`
	}
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	day := aux.DayOfWeek
	if day == 0 {
		day = 7
	}
	if day < 1 || day > 7 {
		return fmt.Errorf("invalid schedule day_of_week %d: must be 1 (monday) to 7 (sunday)", aux.DayOfWeek)
	}
	from, err := parseClock(aux.AvailableFrom)
	if err != nil {
		return fmt.Errorf("invalid schedule available_from: %w", err)
	}
	to, err := parseClock(aux.AvailableTo)
	if err != nil {
		return fmt.Errorf("invalid schedule available_to: %w", err)
	}
	if !from.Before(to) && !isMidnight(to) {
		return fmt.Errorf("invalid schedule %s-%s: start must be before end (use 00:00 as end for midnight)",
			aux.AvailableFrom, aux.AvailableTo)
	}

	s.DayOfWeek = day
	s.AvailableFrom = from
	s.AvailableTo = to
	return nil
}

// parseClock lit une heure "HH:MM" ou "HH:MM:SS".
func parseClock(value string) (time.Time, error) {
	value = strings.TrimSpace(value)
	for _, layout := range []string{"15:04", "15:04:05"} {
		if t, err := time.Parse(layout, value); err == nil {
			return t, nil
		}
	}
	return time.Time{}, fmt.Errorf("%q is not a HH:MM time", value)
}

func isMidnight(t time.Time) bool {
	return t.Hour() == 0 && t.Minute() == 0 && t.Second() == 0
}

// CreateDiscountRequestHelper handles date parsing for CreateDiscountRequest
type CreateDiscountRequestHelper struct {
	DiscountID         string                  `json:"discount_id,omitempty"`
	DiscountName       string                  `json:"discount_name"`
	DiscountDesc       string                  `json:"discount_desc"`
	PreferredOrder     *int                    `json:"preferred_order,omitempty"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      float64                 `json:"discount_value"`
	DiscountUnit       DiscountUnit            `json:"discount_unit"`
	ValidFrom          string                  `json:"valid_from"`         // YYYY-MM-DD format
	ValidTo            *string                 `json:"valid_to,omitempty"` // YYYY-MM-DD format
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity int                     `json:"discounted_quantity"`
	IsCumulative       bool                    `json:"is_cumulative"`
	IsTimeLimited      bool                    `json:"is_time_limited"`
	Available          bool                    `json:"available"`
	Products           []CreateProductRequest  `json:"products,omitempty"`
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"`
	DiscountScope             DiscountScope `json:"discount_scope,omitempty"`
	MaxRedemptions            *int          `json:"max_redemptions,omitempty"`
	MaxRedemptionsPerCustomer *int          `json:"max_redemptions_per_customer,omitempty"`
}

// UnmarshalJSON for CreateDiscountRequest handles date format parsing
func (r *CreateDiscountRequest) UnmarshalJSON(data []byte) error {
	var helper CreateDiscountRequestHelper
	if err := json.Unmarshal(data, &helper); err != nil {
		return err
	}

	r.DiscountID = helper.DiscountID // Will be overwritten by service if empty
	r.DiscountName = helper.DiscountName
	r.DiscountDesc = helper.DiscountDesc
	r.PreferredOrder = 0
	if helper.PreferredOrder != nil {
		r.PreferredOrder = *helper.PreferredOrder
	}
	r.DiscountCode = helper.DiscountCode
	r.OrderType = helper.OrderType
	r.DiscountValue = helper.DiscountValue
	r.DiscountUnit = helper.DiscountUnit
	r.MinOrderValue = helper.MinOrderValue
	r.MinOrderUnit = helper.MinOrderUnit
	r.MaxDiscountValue = helper.MaxDiscountValue
	r.MaxDiscountUnit = helper.MaxDiscountUnit
	r.DiscountedQuantity = helper.DiscountedQuantity
	r.IsCumulative = helper.IsCumulative
	r.IsTimeLimited = helper.IsTimeLimited
	r.Available = helper.Available
	r.Products = helper.Products
	r.Schedules = helper.Schedules
	r.DiscountScope = helper.DiscountScope
	if r.DiscountScope == "" {
		r.DiscountScope = DiscountScopeProduct
	}
	r.MaxRedemptions = helper.MaxRedemptions
	r.MaxRedemptionsPerCustomer = helper.MaxRedemptionsPerCustomer

	// Parse ValidFrom (YYYY-MM-DD format)
	if t, err := time.Parse("2006-01-02", helper.ValidFrom); err == nil {
		r.ValidFrom = t
	}

	// Parse ValidTo (YYYY-MM-DD format)
	if helper.ValidTo != nil {
		if t, err := time.Parse("2006-01-02", *helper.ValidTo); err == nil {
			r.ValidTo = &t
		}
	}

	return nil
}

// isExplicitNull indique si la clé est présente dans le JSON avec la valeur
// null (à distinguer d'une clé absente, « ne pas modifier »).
func isExplicitNull(data []byte, key string) bool {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return false
	}
	value, ok := raw[key]
	return ok && strings.TrimSpace(string(value)) == "null"
}

// UpdateDiscountRequest is the payload for updating a discount
type UpdateDiscountRequest struct {
	DiscountName       *string                 `json:"discount_name,omitempty"`
	DiscountDesc       *string                 `json:"discount_desc,omitempty"`
	PreferredOrder     *int                    `json:"preferred_order,omitempty"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      *float64                `json:"discount_value,omitempty"`
	DiscountUnit       *DiscountUnit           `json:"discount_unit,omitempty"`
	ValidFrom          *time.Time              `json:"valid_from,omitempty"`
	ValidTo            *time.Time              `json:"valid_to,omitempty"`
	// ClearValidTo : "valid_to": null explicite (« Sans limite » dans le
	// back-office) — retire la date de fin. Une clé absente ne modifie rien.
	ClearValidTo       bool                    `json:"-"`
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity *int                    `json:"discounted_quantity,omitempty"`
	IsCumulative       *bool                   `json:"is_cumulative,omitempty"`
	IsTimeLimited      *bool                   `json:"is_time_limited,omitempty"`
	Available          *bool                   `json:"available,omitempty"`
	Products           []CreateProductRequest  `json:"products,omitempty"`  // If provided, replaces all
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"` // If provided, replaces all
	DiscountScope             *DiscountScope `json:"discount_scope,omitempty"`
	MaxRedemptions            *int           `json:"max_redemptions,omitempty"`
	MaxRedemptionsPerCustomer *int           `json:"max_redemptions_per_customer,omitempty"`
}

// UpdateDiscountRequestHelper handles date parsing for UpdateDiscountRequest
type UpdateDiscountRequestHelper struct {
	DiscountName       *string                 `json:"discount_name,omitempty"`
	DiscountDesc       *string                 `json:"discount_desc,omitempty"`
	PreferredOrder     *int                    `json:"preferred_order,omitempty"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      *float64                `json:"discount_value,omitempty"`
	DiscountUnit       *DiscountUnit           `json:"discount_unit,omitempty"`
	ValidFrom          *string                 `json:"valid_from,omitempty"`         // YYYY-MM-DD format
	ValidTo            *string                 `json:"valid_to,omitempty"`           // YYYY-MM-DD format
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity *int                    `json:"discounted_quantity,omitempty"`
	IsCumulative       *bool                   `json:"is_cumulative,omitempty"`
	IsTimeLimited      *bool                   `json:"is_time_limited,omitempty"`
	Available          *bool                   `json:"available,omitempty"`
	Products           []CreateProductRequest  `json:"products,omitempty"`
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"`
	DiscountScope             *DiscountScope `json:"discount_scope,omitempty"`
	MaxRedemptions            *int           `json:"max_redemptions,omitempty"`
	MaxRedemptionsPerCustomer *int           `json:"max_redemptions_per_customer,omitempty"`
}

// UnmarshalJSON for UpdateDiscountRequest handles date format parsing
func (r *UpdateDiscountRequest) UnmarshalJSON(data []byte) error {
	var helper UpdateDiscountRequestHelper
	if err := json.Unmarshal(data, &helper); err != nil {
		return err
	}

	r.DiscountName = helper.DiscountName
	r.DiscountDesc = helper.DiscountDesc
	r.PreferredOrder = helper.PreferredOrder
	r.DiscountCode = helper.DiscountCode
	r.OrderType = helper.OrderType
	r.DiscountValue = helper.DiscountValue
	r.DiscountUnit = helper.DiscountUnit
	r.MinOrderValue = helper.MinOrderValue
	r.MinOrderUnit = helper.MinOrderUnit
	r.MaxDiscountValue = helper.MaxDiscountValue
	r.MaxDiscountUnit = helper.MaxDiscountUnit
	r.DiscountedQuantity = helper.DiscountedQuantity
	r.IsCumulative = helper.IsCumulative
	r.IsTimeLimited = helper.IsTimeLimited
	r.Available = helper.Available
	r.Products = helper.Products
	r.Schedules = helper.Schedules
	r.DiscountScope = helper.DiscountScope
	r.MaxRedemptions = helper.MaxRedemptions
	r.MaxRedemptionsPerCustomer = helper.MaxRedemptionsPerCustomer

	// Parse ValidFrom (YYYY-MM-DD format)
	if helper.ValidFrom != nil {
		if t, err := time.Parse("2006-01-02", *helper.ValidFrom); err == nil {
			r.ValidFrom = &t
		}
	}

	// Parse ValidTo (YYYY-MM-DD format)
	if helper.ValidTo != nil {
		if t, err := time.Parse("2006-01-02", *helper.ValidTo); err == nil {
			r.ValidTo = &t
		}
	}
	r.ClearValidTo = helper.ValidTo == nil && isExplicitNull(data, "valid_to")

	return nil
}

// Validate checks the CreateDiscountRequest validity
func (r *CreateDiscountRequest) Validate() error {
	if r.DiscountName == "" || len(r.DiscountName) > 50 {
		return ErrInvalidDiscountName
	}
	if r.DiscountDesc == "" || len(r.DiscountDesc) > 100 {
		return ErrInvalidDiscountDesc
	}
	if r.DiscountValue < 0 {
		return ErrInvalidDiscountValue
	}
	if r.DiscountUnit != DiscountUnitPercentage && r.DiscountUnit != DiscountUnitCurrency && r.DiscountUnit != DiscountUnitNewPrice {
		return ErrInvalidDiscountUnit
	}
	if r.IsTimeLimited && len(r.Schedules) == 0 {
		return ErrInvalidSchedules
	}
	return nil
}
