package discounts

import (
	"encoding/json"
	"time"
)

// TimeOfDay represents a time of day in HH:MM format for JSON serialization
type TimeOfDay time.Time

// MarshalJSON formats TimeOfDay as "HH:MM"
func (t TimeOfDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(time.Time(t).Format("15:04"))
}

// UnmarshalJSON parses "HH:MM" format from JSON
func (t *TimeOfDay) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	parsed, err := time.Parse("15:04", s)
	if err != nil {
		return err
	}
	*t = TimeOfDay(parsed)
	return nil
}

// DiscountUnit represents the unit type for discount calculation
type DiscountUnit string

const (
	DiscountUnitPercentage DiscountUnit = "PERCENTAGE"
	DiscountUnitCurrency   DiscountUnit = "CURRENCY"
	DiscountUnitNewPrice   DiscountUnit = "NEWPRICE"
)

// OrderType represents the order type for which the discount applies
type OrderType string

const (
	OrderTypeInDining OrderType = "IN"
	OrderTypeDelivery OrderType = "DELIVERY"
)

// MinOrderUnit represents the unit for minimum order requirements
type MinOrderUnit string

const (
	MinOrderUnitCurrency MinOrderUnit = "CURRENCY"
	MinOrderUnitQuantity MinOrderUnit = "QUANTITY"
)

// MaxDiscountUnit represents the unit for maximum discount cap
type MaxDiscountUnit string

const (
	MaxDiscountUnitCurrency MaxDiscountUnit = "CURRENCY"
	MaxDiscountUnitQuantity MaxDiscountUnit = "QUANTITY"
)

// DiscountProduct represents a product associated with a discount and its custom price
type DiscountProduct struct {
	ID         int64  `json:"id"`
	DiscountID int64  `json:"discount_id"`
	ProductID  string `json:"product_id"` // UUID
	NewPrice   *int64 `json:"new_price,omitempty"`
	Enabled    bool   `json:"enabled"`
}

// DiscountSchedule represents time slot availability for a discount
type DiscountSchedule struct {
	ScheduleID    int64     `json:"schedule_id"`
	DiscountID    int64     `json:"discount_id"`
	DayOfWeek     int       `json:"day_of_week"`    // 1 = Sunday, 2 = Monday, etc.
	AvailableFrom TimeOfDay `json:"available_from"` // HH:MM format
	AvailableTo   TimeOfDay `json:"available_to"`   // HH:MM format
	Enabled       bool      `json:"enabled"`
}

// Discount represents a complete discount/promotion
type Discount struct {
	DiscountID         string             `json:"discount_id"`
	MerchantID         string             `json:"merchant_id"`
	DiscountName       string             `json:"discount_name"`
	DiscountDesc       string             `json:"discount_desc"`
	PreferredOrder     int                `json:"preferred_order"`
	DiscountCode       *string            `json:"discount_code,omitempty"`
	OrderType          *OrderType         `json:"order_type,omitempty"` // nil = all types
	DiscountValue      *int               `json:"discount_value"`
	DiscountUnit       DiscountUnit       `json:"discount_unit"`
	ValidFrom          time.Time          `json:"valid_from"`         // UTC
	ValidTo            *time.Time         `json:"valid_to,omitempty"` // UTC
	MinOrderValue      *float64           `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit      `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64           `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit   `json:"max_discount_unit,omitempty"`
	DiscountedQuantity int                `json:"discounted_quantity"`
	IsCumulative       bool               `json:"is_cumulative"`
	IsTimeLimited      bool               `json:"is_time_limited"`
	Available          bool               `json:"available"`
	Enabled            bool               `json:"enabled"`
	CreationDate       time.Time          `json:"creation_date"` // UTC
	Products           []DiscountProduct  `json:"products,omitempty"`
	Schedules          []DiscountSchedule `json:"schedules,omitempty"`
}

// CreateDiscountRequest is the payload for creating a discount
type CreateDiscountRequest struct {
	DiscountID         string                  `json:"discount_id"` // UUID generated by client
	DiscountName       string                  `json:"discount_name"`
	DiscountDesc       string                  `json:"discount_desc"`
	PreferredOrder     int                     `json:"preferred_order"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      float64                 `json:"discount_value"`
	DiscountUnit       DiscountUnit            `json:"discount_unit"`
	ValidFrom          time.Time               `json:"valid_from"`
	ValidTo            *time.Time              `json:"valid_to,omitempty"`
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity int                     `json:"discounted_quantity"`
	IsCumulative       bool                    `json:"is_cumulative"`
	IsTimeLimited      bool                    `json:"is_time_limited"`
	Available          bool                    `json:"available"`
	Products           []CreateProductRequest  `json:"products,omitempty"`
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"`
}

// CreateProductRequest represents product data for discount creation
type CreateProductRequest struct {
	ProductID string `json:"product_id"` // UUID
	NewPrice  *int64 `json:"new_price,omitempty"`
}

// CreateScheduleRequest represents schedule data for discount creation
type CreateScheduleRequest struct {
	DayOfWeek     int       `json:"day_of_week"`
	AvailableFrom time.Time `json:"available_from"`
	AvailableTo   time.Time `json:"available_to"`
}

// UnmarshalJSON parses schedule request with HH:MM time format
func (s *CreateScheduleRequest) UnmarshalJSON(data []byte) error {
	type Alias struct {
		DayOfWeek     int    `json:"day_of_week"`
		AvailableFrom string `json:"available_from"`
		AvailableTo   string `json:"available_to"`
	}
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	s.DayOfWeek = aux.DayOfWeek

	// Parse available_from (HH:MM format)
	if t, err := time.Parse("15:04", aux.AvailableFrom); err == nil {
		s.AvailableFrom = t
	}

	// Parse available_to (HH:MM format)
	if t, err := time.Parse("15:04", aux.AvailableTo); err == nil {
		s.AvailableTo = t
	}

	return nil
}

// CreateDiscountRequestHelper handles date parsing for CreateDiscountRequest
type CreateDiscountRequestHelper struct {
	DiscountID         string                  `json:"discount_id,omitempty"`
	DiscountName       string                  `json:"discount_name"`
	DiscountDesc       string                  `json:"discount_desc"`
	PreferredOrder     *int                    `json:"preferred_order,omitempty"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      float64                 `json:"discount_value"`
	DiscountUnit       DiscountUnit            `json:"discount_unit"`
	ValidFrom          string                  `json:"valid_from"`         // YYYY-MM-DD format
	ValidTo            *string                 `json:"valid_to,omitempty"` // YYYY-MM-DD format
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity int                     `json:"discounted_quantity"`
	IsCumulative       bool                    `json:"is_cumulative"`
	IsTimeLimited      bool                    `json:"is_time_limited"`
	Available          bool                    `json:"available"`
	Products           []CreateProductRequest  `json:"products,omitempty"`
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"`
}

// UnmarshalJSON for CreateDiscountRequest handles date format parsing
func (r *CreateDiscountRequest) UnmarshalJSON(data []byte) error {
	var helper CreateDiscountRequestHelper
	if err := json.Unmarshal(data, &helper); err != nil {
		return err
	}

	r.DiscountID = helper.DiscountID // Will be overwritten by service if empty
	r.DiscountName = helper.DiscountName
	r.DiscountDesc = helper.DiscountDesc
	r.PreferredOrder = 0
	if helper.PreferredOrder != nil {
		r.PreferredOrder = *helper.PreferredOrder
	}
	r.DiscountCode = helper.DiscountCode
	r.OrderType = helper.OrderType
	r.DiscountValue = helper.DiscountValue
	r.DiscountUnit = helper.DiscountUnit
	r.MinOrderValue = helper.MinOrderValue
	r.MinOrderUnit = helper.MinOrderUnit
	r.MaxDiscountValue = helper.MaxDiscountValue
	r.MaxDiscountUnit = helper.MaxDiscountUnit
	r.DiscountedQuantity = helper.DiscountedQuantity
	r.IsCumulative = helper.IsCumulative
	r.IsTimeLimited = helper.IsTimeLimited
	r.Available = helper.Available
	r.Products = helper.Products
	r.Schedules = helper.Schedules

	// Parse ValidFrom (YYYY-MM-DD format)
	if t, err := time.Parse("2006-01-02", helper.ValidFrom); err == nil {
		r.ValidFrom = t
	}

	// Parse ValidTo (YYYY-MM-DD format)
	if helper.ValidTo != nil {
		if t, err := time.Parse("2006-01-02", *helper.ValidTo); err == nil {
			r.ValidTo = &t
		}
	}

	return nil
}

// UpdateDiscountRequest is the payload for updating a discount
type UpdateDiscountRequest struct {
	DiscountName       *string                 `json:"discount_name,omitempty"`
	DiscountDesc       *string                 `json:"discount_desc,omitempty"`
	PreferredOrder     *int                    `json:"preferred_order,omitempty"`
	DiscountCode       *string                 `json:"discount_code,omitempty"`
	OrderType          *OrderType              `json:"order_type,omitempty"`
	DiscountValue      *float64                `json:"discount_value,omitempty"`
	DiscountUnit       *DiscountUnit           `json:"discount_unit,omitempty"`
	ValidFrom          *time.Time              `json:"valid_from,omitempty"`
	ValidTo            *time.Time              `json:"valid_to,omitempty"`
	MinOrderValue      *float64                `json:"min_order_value,omitempty"`
	MinOrderUnit       *MinOrderUnit           `json:"min_order_unit,omitempty"`
	MaxDiscountValue   *float64                `json:"max_discount_value,omitempty"`
	MaxDiscountUnit    *MaxDiscountUnit        `json:"max_discount_unit,omitempty"`
	DiscountedQuantity *int                    `json:"discounted_quantity,omitempty"`
	IsCumulative       *bool                   `json:"is_cumulative,omitempty"`
	IsTimeLimited      *bool                   `json:"is_time_limited,omitempty"`
	Available          *bool                   `json:"available,omitempty"`
	Products           []CreateProductRequest  `json:"products,omitempty"`  // If provided, replaces all
	Schedules          []CreateScheduleRequest `json:"schedules,omitempty"` // If provided, replaces all
}

// Validate checks the CreateDiscountRequest validity
func (r *CreateDiscountRequest) Validate() error {
	if r.DiscountName == "" || len(r.DiscountName) > 50 {
		return ErrInvalidDiscountName
	}
	if r.DiscountDesc == "" || len(r.DiscountDesc) > 100 {
		return ErrInvalidDiscountDesc
	}
	if r.DiscountValue < 0 {
		return ErrInvalidDiscountValue
	}
	if r.DiscountUnit != DiscountUnitPercentage && r.DiscountUnit != DiscountUnitCurrency && r.DiscountUnit != DiscountUnitNewPrice {
		return ErrInvalidDiscountUnit
	}
	if r.IsTimeLimited && len(r.Schedules) == 0 {
		return ErrInvalidSchedules
	}
	return nil
}
